### ISSUE TITLE
PulMetadataServices::Client.bibdata? validates unpublished bib. IDs

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pul_metadata_services#32]
While it may validate the structure of bib. IDs, it does not indicate whether or not these currently reference any actively published bib. records:
```
[3] pry(main)> PulMetadataServices::Client.bibdata?('invalid')
=> nil
[4] pry(main)> PulMetadataServices::Client.bibdata?('001')
=> 0
```

Yet, this does not resolve: https://catalog.princeton.edu/catalog/001.json

**Comment by tpendragon** [comment]
This seems fine to me - the purpose of this method is just to check if it should be -trying- to get the info from bibdata or if it should be trying to get the info from pulfa.
