### ISSUE TITLE
date_from_008

### ISSUE THREAD

**Issue by tampakis** [pulibrary/pul_metadata_services#7]
Should the date_from_008 method from [here](https://github.com/pulibrary/pul_metadata_services/blob/master/lib/pul_metadata_services/bib_record.rb#L267-L270) look the same as the one in [orangeindex](https://github.com/pulibrary/orangeindex/blob/development/lib/princeton_marc.rb#L47-L54)? The orangeindex method accounts for blanks in the 008 field, and if the value is `uuuu` or `0000` it returns nil.

A lot of the MARC extraction code in general looks like behavior it should share with orangeindex.

**Comment by jpstroop** [comment]
> A lot of the MARC extraction code in general looks like behavior it should share with orangeindex.

Yes, I'd love for that to be the case. That said, this is primarly for lighter-weight indexing and display than OrangeLight is concerned with. If you can think of a way these behaviors can be shared, I'd love to hear it.

**Comment by tampakis** [comment]
I think we should discuss which marc fields both projects use to at least make sure that the index/display values are consistent. Then if it make sense, find a common home for these behaviors. Maybe it can be a service bibdata provides?

**Comment by jpstroop** [comment]
That feels like a potential enhancement that we should keep in mind.
Remember that, at least in this initial iteration, public users will
discover these resources via Blacklight, and so they'll already be
interacting with a richer treatment of the MARC data.

-Js

Sent via mobile. Please excuse typos, brevity, etc.
